### ISSUE TITLE
allow SYNCHRONOUS_OUTPUT to be set separately for each logger in runtime

### ISSUE THREAD

**Issue by n506** [zsummer/log4z#32]
its feature request
thank you

**Comment by zsummer** [comment]
mark

**Comment by zsummer** [comment]
I review log4z code and I remember why it's all logger when I design this define. 
log4z's loggers count is dynamic in runtime.  if I set it separately for each logger. then the problem is show up that is  user can switch 'output' option in runtime , and ,  one log file can open frome two place two thread.  I think it's danger.
